from __future__ import annotations

from dataclasses import dataclass


Decision = str


@dataclass(frozen=True)
class ExperimentDecisionInput:
    srm_mismatch: bool
    primary_effect: float
    primary_ci_low: float
    primary_ci_high: float
    minimum_useful_effect: float
    guardrail_effect: float
    maximum_guardrail_harm: float


@dataclass(frozen=True)
class ExperimentDecision:
    decision: Decision
    reasons: tuple[str, ...]
    data_scope: str = "synthetic"

    def to_markdown(self) -> str:
        reason_lines = "\n".join(f"- {reason}" for reason in self.reasons)
        return (
            "# Experiment decision\n\n"
            f"**Decision:** `{self.decision}`\n\n"
            "**Evidence scope:** synthetic scenario generated by ExperimentLab.\n\n"
            "## Reasons\n\n"
            f"{reason_lines}\n"
        )


def decide_experiment(inputs: ExperimentDecisionInput) -> ExperimentDecision:
    """Apply explicit validity, usefulness, and guardrail rules to an experiment.

    The primary interval is assumed to represent treatment minus control. A positive guardrail
    effect represents harm when the guardrail is an undesirable outcome such as support contact.
    """

    if inputs.primary_ci_low > inputs.primary_ci_high:
        raise ValueError("primary confidence interval is invalid")
    if inputs.maximum_guardrail_harm < 0:
        raise ValueError("maximum_guardrail_harm must be non-negative")

    if inputs.srm_mismatch:
        return ExperimentDecision(
            decision="hold",
            reasons=(
                "Assignment integrity failed the Sample Ratio Mismatch gate.",
                (
                    "Treatment-effect estimates are not used for shipping while "
                    "randomization is suspect."
                ),
            ),
        )

    if inputs.guardrail_effect > inputs.maximum_guardrail_harm:
        return ExperimentDecision(
            decision="do_not_ship",
            reasons=(
                (
                    "Observed guardrail harm exceeds the pre-specified maximum acceptable "
                    f"increase ({inputs.maximum_guardrail_harm:.4f})."
                ),
                "Primary-metric upside does not override an explicit guardrail breach.",
            ),
        )

    if inputs.primary_ci_low >= inputs.minimum_useful_effect:
        return ExperimentDecision(
            decision="ship",
            reasons=(
                (
                    "The full primary-metric confidence interval is at or above the "
                    f"minimum useful effect ({inputs.minimum_useful_effect:.4f})."
                ),
                "No configured guardrail breach was observed.",
            ),
        )

    if inputs.primary_ci_high < inputs.minimum_useful_effect:
        return ExperimentDecision(
            decision="do_not_ship",
            reasons=(
                (
                    "The full primary-metric confidence interval is below the minimum useful "
                    f"effect ({inputs.minimum_useful_effect:.4f})."
                ),
                "The evidence does not support the pre-specified business-value threshold.",
            ),
        )

    return ExperimentDecision(
        decision="hold",
        reasons=(
            "The primary confidence interval crosses the minimum useful effect threshold.",
            "More evidence is required before making a ship/no-ship recommendation.",
        ),
    )
